apps/teams_web/lib/teams_web/router.ex
defmodule TeamsWeb.Router do
  use TeamsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticate do
    plug TeamsWeb.RequireTeamManagerPlug
  end

  scope "/teams/", TeamsWeb do
    pipe_through(:browser)

    get("/sign_in", SessionController, :new)
    post("/sign_in", SessionController, :create)
    delete("/sign_out", SessionController, :delete)
  end

  scope "/teams", TeamsWeb do
    pipe_through([:browser, :authenticate])

    get("/", TeamController, :index)
    post("/team_members", TeamController, :add_member)
    delete("/team_members/:specialist_id", TeamController, :remove_member)
  end
end

apps/teams_web/lib/teams_web/controllers/page_controller.ex
defmodule TeamsWeb.PageController do
  use TeamsWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/teams_web/lib/teams_web/controllers/session_controller.ex
defmodule TeamsWeb.SessionController do
  use TeamsWeb, :controller

  def new(conn, _) do
    render(conn, "new.html")
  end

  def create(conn, %{"identifier" => identifier, "password" => password}) do
    case Teams.Authentication.team_id(identifier, password) do
      {:ok, team_id} ->
        conn
        |> put_flash(:info, "Signed in")
        |> put_session(:team_id, team_id)
        |> redirect(to: "/teams")

      {:error, _} ->
        conn
        |> put_flash(:error, "Invalid credentials")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> put_flash(:info, "Signed out")
    |> delete_session(:team_id)
    |> redirect(to: "/teams/sign_in")
  end
end

apps/teams_web/lib/teams_web/controllers/team_controller.ex
defmodule TeamsWeb.TeamController do
  use TeamsWeb, :controller

  def index(conn, _params) do
    team_id = conn.assigns.team_id

    members = Teams.get_members(team_id)

    {:ok, profiles} =
      members
      |> Enum.map(& &1.specialist_id)
      |> SpecialistProfile.fetch_basic_infos()

    render(conn, "index.html", team_members: profiles)
  end

  def add_member(conn, params) do
    team_id = conn.assigns.team_id
    email = params["team_invitation"]["email"]

    with {:ok, specialist} <- Authentication.Specialist.fetch_by_email(email),
         :ok <- Teams.add_to_team(team_id: team_id, specialist_id: specialist.id) do
      conn
      |> put_flash(:info, "Specialist added to the team")
      |> redirect(to: "/teams")
    else
      {:error, :already_in_a_team} ->
        conn
        |> put_flash(:error, "The specialist is already in a different team.")
        |> redirect(to: "/teams")

      {:error, :not_found} ->
        conn
        |> put_flash(:error, "Specialist not found")
        |> redirect(to: "/teams")
    end
  end

  def remove_member(conn, %{"specialist_id" => specialist_id}) do
    team_id = conn.assigns.team_id

    :ok = Teams.remove_from_team(team_id: team_id, specialist_id: specialist_id)

    conn
    |> put_flash(:info, "Specialist removed from the team")
    |> redirect(to: "/teams")
  end
end

apps/teams_web/lib/teams_web/views/error_view.ex
defmodule TeamsWeb.ErrorView do
  use TeamsWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/teams_web/lib/teams_web/views/layout_view.ex
defmodule TeamsWeb.LayoutView do
  use TeamsWeb, :view
end

apps/teams_web/lib/teams_web/views/page_view.ex
defmodule TeamsWeb.PageView do
  use TeamsWeb, :view
end

apps/teams_web/lib/teams_web/views/session_view.ex
defmodule TeamsWeb.SessionView do
  use TeamsWeb, :view
end

apps/teams_web/lib/teams_web/views/team_view.ex
defmodule TeamsWeb.TeamView do
  use TeamsWeb, :view
end

apps/teams_web/lib/teams_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>DrOnline Teams</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= Phoenix.Flash.get(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= Phoenix.Flash.get(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/teams_web/lib/teams_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed and maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>

apps/teams_web/lib/teams_web/templates/session/new.html.eex
<h1>Sign in to manage your team</h1>

<%=  form_for @conn, Routes.session_path(@conn, :create), fn f -> %>
  <%= text_input f, :identifier, placeholder: "Identifier" %>
  <%= password_input f, :password %>
  <%= submit "Sign in" %>
<% end %>

apps/teams_web/lib/teams_web/templates/team/index.html.eex
<h1>Manage your team</h1>

<h2>Your team members</h2>

<ul>
  <%= for member <- @team_members do %>
    <li>
      <%= "#{member.first_name} #{member.last_name}" %>
      (<%= link "Delete", to: Routes.team_path(@conn, :remove_member, member.specialist_id), method: :delete %>)
    </li>
  <% end %>
</ul>

<h2>Add team member</h2>

<%= form_for @conn, Routes.team_path(@conn, :add_member), [as: :team_invitation], fn f -> %>
  <%= text_input f, :email, placeholder: "Email address" %>
  <%= submit "Add" %>
<% end %>

<hr />

<%= link "Sign out", to: Routes.session_path(@conn, :delete), method: :delete %>